version: 2.1
jobs:
  android:
    working_directory: ~/darkknight
    docker:
      - image: reactnativecommunity/react-native-android
    steps:
      - checkout
      - run: npx envinfo
      - run: yarn install
      # daemon mode has bug on circleCI
      - run: cd darkknight/android && chmod +x gradlew && ./gradlew --no-daemon bundleRelease assembleRelease
      - run: cd darkknight/android/app/build/outputs/apk/release && ls && pwd
      - store_artifacts:
          path: darkknight/android/app/build/outputs/bundle/release
          destination: release-aab/
      - store_artifacts:
          path: darkknight/android/app/build/outputs/apk/release
          destination: release-apk/

workflows:
  version: 2
  build_and_test:
    jobs:
      - android